Controllers/RestaurantTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheRongRestaurant;
using TheRongRestaurant.Data;

namespace TheRongRestaurant.Controllers
{
    public class RestaurantTableController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RestaurantTableController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RestaurantTable
        public async Task<IActionResult> Index()
        {
            return _context.Tables != null ?
                        View(await _context.Tables.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Tables'  is null.");
        }

        // GET: RestaurantTable/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tables == null)
            {
                return NotFound();
            }

            var restaurantTable = await _context.Tables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurantTable == null)
            {
                return NotFound();
            }

            return View(restaurantTable);
        }

        // GET: RestaurantTable/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RestaurantTable/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TableName,IsOccupied")] RestaurantTable restaurantTable)
        {
            if (ModelState.IsValid)
            {
                _context.Add(restaurantTable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(restaurantTable);
        }

        // GET: RestaurantTable/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tables == null)
            {
                return NotFound();
            }

            var restaurantTable = await _context.Tables.FindAsync(id);
            if (restaurantTable == null)
            {
                return NotFound();
            }
            return View(restaurantTable);
        }

        // POST: RestaurantTable/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TableName,IsOccupied")] RestaurantTable restaurantTable)
        {
            if (id != restaurantTable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restaurantTable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantTableExists(restaurantTable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(restaurantTable);
        }

        // GET: RestaurantTable/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tables == null)
            {
                return NotFound();
            }

            var restaurantTable = await _context.Tables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurantTable == null)
            {
                return NotFound();
            }

            return View(restaurantTable);
        }

        // POST: RestaurantTable/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tables == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Tables'  is null.");
            }
            var restaurantTable = await _context.Tables.FindAsync(id);
            if (restaurantTable != null)
            {
                _context.Tables.Remove(restaurantTable);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantTableExists(int id)
        {
            return (_context.Tables?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public IActionResult Search(string searchTerm)
        {
            if (string.IsNullOrEmpty(searchTerm))
            {
                var allTables = _context.Tables.ToList();
                return View("Index", allTables);
            }

            var searchResults = _context.Tables
                .Where(table => EF.Functions.Like(table.TableName!, $"%{searchTerm}%"))
                .ToList();

            return View("Index", searchResults);
        }
    }
}

Views/RestaurantTable/Create.cshtml
@model TheRongRestaurant.RestaurantTable

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>RestaurantTable</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TableName" class="control-label"></label>
                <input asp-for="TableName" class="form-control" />
                <span asp-validation-for="TableName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsOccupied" /> @Html.DisplayNameFor(model => model.IsOccupied)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/RestaurantTable/Delete.cshtml
@model TheRongRestaurant.RestaurantTable

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RestaurantTable</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TableName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TableName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsOccupied)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsOccupied)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/RestaurantTable/Details.cshtml
@model TheRongRestaurant.RestaurantTable

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RestaurantTable</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TableName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TableName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsOccupied)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsOccupied)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/RestaurantTable/Edit.cshtml
@model TheRongRestaurant.RestaurantTable

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RestaurantTable</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TableName" class="control-label"></label>
                <input asp-for="TableName" class="form-control" />
                <span asp-validation-for="TableName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsOccupied" /> @Html.DisplayNameFor(model => model.IsOccupied)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/RestaurantTable/Index.cshtml
@model IEnumerable<TheRongRestaurant.RestaurantTable>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@using (Html.BeginForm("Search", "RestaurantTable", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="form-group mb-2">
        <label for="searchTerm" class="sr-only">Search by Table Name</label>
        <input type="text" class="form-control" id="searchTerm" name="searchTerm" placeholder="Search by Table Name">
    </div>
    <button type="submit" class="btn btn-primary mb-2">Search</button>
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TableName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsOccupied)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TableName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsOccupied)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>